# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # Orbs reduce the amount of configuration required for common tasks.
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/node
  node: circleci/node@4.7
  docker: circleci/docker@2.0.1

jobs:
  # Below is the definition of your job to build and test your app, you can rename and customize it as you want.
  build-and-push:
    environment:
      DOCKER_IMAGE: myapp
      DOCKER_TAG: latest
      DOCKER_USERNAME: idtruoc
      DOCKER_PASSWORD: imnotFine0
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: build-push-docker-image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG .
            docker images
            docker push $DOCKER_USERNAME/$DOCKER_IMAGE:$DOCKER_TAG
  

workflows:
  my-workflow:
    #  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    #    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build-and-push


